# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(verbose_name='date and time published')),
                ('x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
